query getBids($auctionUUID: String!, $page: Int = 0, $size: Int = 4) {
  bids(auctionUUID: $auctionUUID, page: $page, limit: $size) {
    items {
      id
      amount
      sub
      date
    }
    total
  }
}
