query companiesByOrgID($organisationID: String!) {
  companyByOrganisationID(organisationID: $organisationID) {
    name
    id
    phoneMobile
    email
    city {
      cityName
    }
    state {
      name
    }
    country {
      countryName
    }
    aboutUs
    webSite
    companyLogo {
      aPIID
    }
  }
}
