query meQuery {
  mev2 {
    user {
      id
      subject
      profile {
        userID
        fullName
        title
        pictureURL
        email
        phoneMobile
      }
    }
    primaryRole
    isPremium
    isEnterpriseUser
    roles
  }
}
