query organisationByID($orgId: String) {
  companyByOrganisationID(organisationID: $orgId) {
    name
    id
    organisationID
    email
    phoneMobile
    webSite
    link
    country {
      id
      countryName
      countryCode
      phoneCode
    }
    description
    aboutUs
    city {
      id
      cityName
    }
  }
}
