query seeUserProfileBySubject($subject: String!) {
  seeUserProfileBySubject(subject: $subject) {
    user {
      subject
      userID
      fullName
      isSearchable
      title
      aboutMe
      nationality
      dateOfBirth
      gender
      residentCardNo
      phoneMobile
      phoneHome
      phoneMobile
      email
      createdDate
      deletedDate
      lastLoginDate
      isActive
      isLocked
      firstName
      middleName
      lastName
      country {
        id
        countryName
        countryCode
        phoneCode
        nationality
      }
      bkgImg #{
      #id
      #aPIID
      # aPIURL
      # aPISize
      # aPIBucket
      # aPIObject
      # aPIFilename
      #}
      photo {
        id
        aPIID
        aPIURL
        aPISize
        aPIBucket
        aPIObject
        aPIFilename
      }
    }
  }
}
