module.exports = {
  OAUTH_CLIENT_ID: JSON.stringify('meera-dx'),
  OAUTH_CLIENT_SECRET: JSON.stringify('DzXZxyDObSpsnR7qLqQ4p1LEVoIiE49e'),
  OAUTH_HOST: JSON.stringify('https://sso.test.meeraspace.com'),
  OAUTH_CALLBACK_HOST: JSON.stringify('https://profile.test.meeraspace.com'),
  // GRPC_API: JSON.stringify('https://example.com/grpc'),
  // GRAPHQL_API: JSON.stringify('https://example.com/graphql'),
  // API_KEYWORDS: JSON.stringify(['example.com']),
  PRODUCT_APP_URL_PROFILE: JSON.stringify('https://profile.test.meeraspace.com'),
  PRODUCT_APP_URL_API: JSON.stringify('https://api.test.meeraspace.com'),
  PRODUCT_WORKSPACE_URL: JSON.stringify('https://test.meeraspace.com'),
  PRODUCT_APP_URL_PLANNER: JSON.stringify('https://planner.test.meeraspace.com'),
  PRODUCT_APP_URL_CONFIGURATOR: JSON.stringify(
    'https://configurator.test.meeraspace.com',
  ),
  PRODUCT_APP_URL_EDGE: JSON.stringify('https://edge.test.meeraspace.com'),
  PRODUCT_APP_URL_OKR: JSON.stringify('https://okr.test.meeraspace.com'),
  PRODUCT_APP_URL_HCM: JSON.stringify('https://hcm.test.meeraspace.com'),
  ENV_VAR_ME_TO: JSON.stringify('https://profile.test.meeraspace.com'),
  PRODUCT_APP_URL_PULSE: JSON.stringify(
    'https://demo-ams-01.digitalenergycloud.com',
  ),
  PRODUCT_APP_URL_REACH: JSON.stringify(
    'https://demo-reach-01.digitalenergycloud.com',
  ),
  PRODUCT_APP_URL_TROVE: JSON.stringify('https://trove.test.meeraspace.com'),
  PRODUCT_APP_URL_ORGANIZATION: JSON.stringify(
    'https://organization.test.meeraspace.com',
  ),
  MEETING_URL: JSON.stringify('https://meeting.test.meeraspace.com'),
  PRODUCT_APP_URL_CRM: JSON.stringify('https://manager.test.meeraspace.com'),
  PRODUCT_APP_URL_LANG: JSON.stringify('https://i18n.test.meeraspace.com'),
  PRODUCT_APP_URL_PSA: JSON.stringify('https://psa.test.meeraspace.com'),
  PRODUCT_APP_URL_BI: JSON.stringify('https://bi.test.meeraspace.com'),
  PRODUCT_APP_URL_REGULATION: JSON.stringify('https://cm.test.meeraspace.com'),
  PRODUCT_APP_URL_PEOPLEANALYTICS: JSON.stringify(
    'https://peopleanalytics.test.meeraspace.com',
  ),
  PRODUCT_APP_URL_TIMESHEET: JSON.stringify(
    'https://timesheet.test.meeraspace.com',
  ),
  PRODUCT_APP_URL_AMC: JSON.stringify('https://amc.test.meeraspace.com'),
  PRODUCT_APP_URL_MAP: JSON.stringify('https://map.test.meeraspace.com'),
  PRODUCT_APP_URL_PDO: JSON.stringify('https://pdo.test.meeraspace.com'),
  PRODUCT_APP_URL_CSR: JSON.stringify('https://csr.test.meeraspace.com'),
  BASE_ENV_URL: JSON.stringify('https://test.meeraspace.com'),
  PRODUCT_APP_URL_REGION: JSON.stringify('https://gregion.test.meeraspace.com'),
  PRODUCT_APP_URL_FLUXBLE_MEETING: JSON.stringify(
    'https://venue.test.meeraspace.com',
  ),
  PRODUCT_APP_URL_WORKSPACE: JSON.stringify('https://test.meeraspace.com'),
  TOKEN_DOMAIN: JSON.stringify('https://test.meeraspace.com'),
  PRODUCT_APP_URL_DSO: JSON.stringify('https://dso.test.meeraspace.com'),
  PRODUCT_APP_URL_AUCTION: JSON.stringify(
    'https://auctions.test.meeraspace.com',
  ),
  DASHBOARD_ID_DSO: JSON.stringify('np9s4cvNsERhFx1PLDPJo'),
  OVERWRITE_TRANSLATION: JSON.stringify(''),
  PRODUCT_APP_URL_API_WEBSOCKET: JSON.stringify('wss://api.test.meeraspace.com'),
}
