module.exports = {
  OAUTH_CLIENT_SECRET: JSON.stringify('DzXZxyDObSpsnR7qLqQ4p1LEVoIiE49e'),
  OAUTH_CLIENT_ID: JSON.stringify('meera-dx'),
  OAUTH_HOST: JSON.stringify('https://sso-v2.dev.meeraspace.com'),
  OAUTH_CALLBACK_HOST: JSON.stringify('https://profile.dev.meeraspace.com'),
  // GRPC_API: JSON.stringify('https://example.com/grpc'),
  // GRAPHQL_API: JSON.stringify('https://example.com/graphql'),
  // API_KEYWORDS: JSON.stringify(['example.com']),
  PRODUCT_APP_URL_PROFILE: JSON.stringify('https://profile.dev.meeraspace.com'),
  PRODUCT_APP_URL_API: JSON.stringify('https://api.dev.meeraspace.com'),
  PRODUCT_WORKSPACE_URL: JSON.stringify('https://dev.meeraspace.com'),
  PRODUCT_APP_URL_PLANNER: JSON.stringify('https://planner.dev.meeraspace.com'),
  PRODUCT_APP_URL_CONFIGURATOR: JSON.stringify(
    'https://configurator.dev.meeraspace.com',
  ),
  PRODUCT_APP_URL_EDGE: JSON.stringify('https://edge.dev.meeraspace.com'),
  PRODUCT_APP_URL_OKR: JSON.stringify('https://okr.dev.meeraspace.com'),
  PRODUCT_APP_URL_HCM: JSON.stringify('https://hcm.dev.meeraspace.com'),
  ENV_VAR_ME_TO: JSON.stringify('https://profile.dev.meeraspace.com'),
  PRODUCT_APP_URL_PULSE: JSON.stringify(
    'https://demo-ams-01.digitalenergycloud.com',
  ),
  PRODUCT_APP_URL_REACH: JSON.stringify(
    'https://demo-reach-01.digitalenergycloud.com',
  ),
  PRODUCT_APP_URL_TROVE: JSON.stringify('https://trove.dev.meeraspace.com'),
  PRODUCT_APP_URL_ORGANIZATION: JSON.stringify(
    'https://organization.dev.meeraspace.com',
  ),
  MEETING_URL: JSON.stringify('https://meeting.dev.meeraspace.com'),
  PRODUCT_APP_URL_CRM: JSON.stringify('https://manager.dev.meeraspace.com'),
  PRODUCT_APP_URL_LANG: JSON.stringify('https://i18n.dev.meeraspace.com'),
  PRODUCT_APP_URL_PSA: JSON.stringify('https://psa.dev.meeraspace.com'),
  PRODUCT_APP_URL_BI: JSON.stringify('https://bi.dev.meeraspace.com'),
  PRODUCT_APP_URL_REGULATION: JSON.stringify('https://cm.dev.meeraspace.com'),
  PRODUCT_APP_URL_PEOPLEANALYTICS: JSON.stringify(
    'https://peopleanalytics.dev.meeraspace.com',
  ),
  PRODUCT_APP_URL_TIMESHEET: JSON.stringify(
    'https://timesheet.dev.meeraspace.com',
  ),
  PRODUCT_APP_URL_AMC: JSON.stringify('https://amc.dev.meeraspace.com'),
  PRODUCT_APP_URL_MAP: JSON.stringify('https://map.dev.meeraspace.com'),
  PRODUCT_APP_URL_PDO: JSON.stringify('https://pdo.dev.meeraspace.com'),
  PRODUCT_APP_URL_CSR: JSON.stringify('https://csr.dev.meeraspace.com'),
  BASE_ENV_URL: JSON.stringify('https://dev.meeraspace.com'),
  PRODUCT_APP_URL_REGION: JSON.stringify('https://gregion.dev.meeraspace.com'),
  PRODUCT_APP_URL_FLUXBLE_MEETING: JSON.stringify(
    'https://venue.dev.meeraspace.com',
  ),
  PRODUCT_APP_URL_WORKSPACE: JSON.stringify('https://dev.meeraspace.com'),
  TOKEN_DOMAIN: JSON.stringify('https://dev.meeraspace.com'),
  PRODUCT_APP_URL_DSO: JSON.stringify('https://dso.dev.meeraspace.com'),
  PRODUCT_APP_URL_AUCTION: JSON.stringify(
    'https://auctions.dev.meeraspace.com',
  ),
  DASHBOARD_ID_DSO: JSON.stringify('np9s4cvNsERhFx1PLDPJo'),
  OVERWRITE_TRANSLATION: JSON.stringify(''),
  PRODUCT_APP_URL_API_WEBSOCKET: JSON.stringify('wss://api.dev.meeraspace.com'),
}
