export const dummyData = [
  {
    id: '1',
    auction_end_date: '12-12-2020',
    awarded_to: { uuid: 'jj' },
    auction_start_date: '12-12-2020',
    starting_price: '10',
    name: 'villa 1',
    location: 'jumeirah',
    isHighestBid: true,
    url: 'https://picsum.photos/200',
  },
  {
    id: '2',
    auction_end_date: '12-12-2020',
    awarded_to: { uuid: 'jj' },
    auction_start_date: '12-12-2020',
    starting_price: '10',
    name: 'villa 2',
    location: 'jumeirah',
    url: 'https://picsum.photos/200',
  },
  {
    id: '3',
    auction_end_date: '12-12-2020',
    awarded_to: { uuid: 'jj' },
    auction_start_date: '12-12-2020',
    starting_price: '10',
    name: 'villa 3',
    location: 'jumeirah',
    url: 'https://picsum.photos/200',
  },
]
